apiVersion: "v1"
kind: "Service"
metadata:
  name: "microblog-frontend"
  labels:
    app: "microblog-frontend"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "microblog-frontend"
  type: "ClusterIP"
